#!/bin/sh

[ -r ../conf ] && . ../conf

if [ ${LOGGING_ENABLE} = 1 ]; then
    [ -d "${LOG_DIR}" ] || mkdir -p "${LOG_DIR}"

    exec svlogd -tt "${LOG_DIR}"
else
    exec chpst -b wireplumber-log-null cat >/dev/null
fi
