#!/bin/sh

SVDIR=~/.config/runit/services

# pipewire dependency
sv check "$SVDIR/pipewire" >/dev/null || exit 1

[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE}" = "1" -a -n "${LOG_LEVEL}" ]; then
    export WIREPLUMBER_DEBUG="${LOG_LEVEL}"
fi

export XDG_RUNTIME_DIR=/run/user/1000

exec dbus-run-session wireplumber ${OPTS:-} 4>&1

